Add remove todos
kamranahmad123/To-Do-Structure pull request #4
Opened 2023-02-24 18:07 UTC by kamranahmad123

1- Add dynamic functions to, to-do-list.
2- Add remove and add functionalities to the list

2023-02-24 19:50 UTC, BenMukebo requested changes
### Hi @kamranahmad123,

You did a great job so far 👏🏼 👏🏼
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

### To highlight 💪🏻
- GitHub flow was correctly used.  ✔️   
 👍  Good job!


## STATUS: CHANGES REQUESTED  ♻️ 
_Please Check the comments under the review and make all required changes_

- [ ]  Let's try to be thorough in our documentation. This is a `To Do list` project, but your README contains information describing the `Awesome Books `. I'd suggest you fix the title of your project and  add a meaningful `Project description`. Remember A project description is a high-level overview of why you're doing a project. 😉 💯 

![image](https://user-images.githubusercontent.com/79058364/221262857-7c8e06ec-ae41-4e63-ab89-772ec275f385.png)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏 💻  
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me @BenMukebo when you comment so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-24 19:50 UTC, BenMukebo commented on src/newFunctionalities.js
> +// eslint-disable-next-line import/no-mutable-exports
- [ ] It is always a good practice to make sure you fix all linter errors instead of disabling them, A linter is great for identifying errors when you use standard rules. Remember, a linter analyzes your code for stylistic and programming errors against the rules it knows. 💯 😉

2023-02-24 19:50 UTC, BenMukebo commented on src/newFunctionalities.js
> +    element.index = i + 1;
- [ ] Actually, there is nothing that works 👇🏻 

[Screencast from 02-24-2023 09:43:58 PM.webm](https://user-images.githubusercontent.com/79058364/221276368-00434e38-19fb-4fb4-88a8-89016202acb8.webm)

Kindly make sure:
1. A function for adding a new book is well implemented. ✔️   
2. A function for editing task descriptions is well implemented. ✔️   
3. A function for remove a book from the array is implemented. ✔️   
4.  Deleting a task should update all remaining items' indexes, so they represent the current list order and are unique. ✔️   
5. All changes to the To-Do List should be saved in local storage. ✔️

2023-02-25 02:41 UTC, kamranahmad123 commented
1- As I have checked the buttons and options were working fine, as a result I attaching a link.
https://www.loom.com/share/e70a4516d6dd4271ad7b7f45301b3acb

2023-02-25 04:15 UTC, amon-cofie requested changes
Hi @kamranahmad123 , 

Great work! You really have done a great job 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

<img src="https://media0.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

 ## Highlights
🚀 Good commit messages
🚀 Github flow used


 ## Required Changes ♻️

You have done exceptional work on this project 👍 However, the link you presented in your readme to view your project live does not have any functionality and is static. Also there is no start script in your package.json file to start the project on the local server so as to verify the existence of the functionality. Please ensure that you installed everything correctly. Your package.json file: 
![image](https://user-images.githubusercontent.com/107795045/221335409-167adb69-ffd7-45ec-ba51-94ba6e3c0b0a.png)

It will be very helpful if you add to your documentation how a user of your app can start it on a local server 😉 
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-25 04:15 UTC, amon-cofie commented on src/newFunctionalities.js
> +// eslint-disable-next-line import/no-mutable-exports
As a matter of fact @kamranahmad123, this linter assertion is one of the most important ones there are. What it means is that you should make sure that what you are exporting cannot be changed as this can break your app under certain circumstances. In your case, you declare tasksData with the let keyword which can be mutated and thus, not preferrable. I think it would be a good idea to refactor this array so that it is not exporting as a mutable array. Here is a tip: You can declare an array with the const keyword and use the ```.push()``` method if you have to add to it or ```.filter()``` if you have to remove from it. The only thing that causes an issue in this case is if you try to re-assign anything to the same variable as the array 😉

2023-02-25 10:01 UTC, AbayomiOlaoye requested changes
Hi @kamranahmad123 👋 , 

Great work on making the changes requested by a previous reviewer 👏 
I kinda believe that you will get it sorted in the next round with this impressive pace you are exuding 💪 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![so_close](https://user-images.githubusercontent.com/99715640/211872359-9a4d36f7-0386-4000-82a4-c274b06a5ce4.gif)


 ## Highlights
- Good response to suggestions/feedback ✅ 
- No linter error ✅ 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-25 10:01 UTC, AbayomiOlaoye commented on src/index.html
> +        <!-- <img  class='refreshButton' src="./Refresh.png"> -->
- [ ] It's good you have attempted suggested changes but you seem to have forgotten about your clean code principle. Having unused pieces of codes as comments in our code base isn't a good practice. It messes up the appearance of our code and reduces understandability 🔧 
- Kindly remove the comments 🙏 (there's another unused code on line 7 😉 )

2023-02-25 10:01 UTC, AbayomiOlaoye commented on src/index.html
> +            <!-- <i class ="addButton fa-solid fa-turn-down-left"></i> -->
- [ ] It's good you have attempted suggested changes but you seem to have forgotten about your clean code principle. Having unused pieces of codes as comments in our code base isn't a good practice. It messes up the appearance of our code and reduces understandability 🔧 
- Kindly remove the comments 🙏

2023-02-25 10:01 UTC, AbayomiOlaoye commented on webpack.config.js
>        {
- [ ] Kindly check your configuration as there seems to be a conflict in the bundling of your code for production. Here is a guide that might help:

![image](https://user-images.githubusercontent.com/99715640/221350850-e1da62e1-b21b-49de-a087-eac9952a97ad.png)

- For good performance, kindly check and fix this bug

2023-02-25 11:15 UTC, kamranahmad123 commented on webpack.config.js
>        {
I have executed this function again and again and it gives no error.

2023-02-25 11:47 UTC, AbayomiOlaoye commented on webpack.config.js
>        {
That's beautiful! Once the comments have been removed, please submit again. Sorry, man!

2023-02-27 10:20 UTC, m05e5 approved these changes
**Hi @kamranahmad123 
You did great. Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![CleverScornfulBuffalo-size_restricted](https://user-images.githubusercontent.com/37901469/208869296-5ca9f6cc-a1b5-48fd-bd59-78fd83b35471.gif)

## Highlights

✔️ Clean and well-organized code
✔️ No Linters error

## Optional suggestions



_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

_**m05e5**_

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._**

2023-02-27 10:22 UTC, merged